baseURL = "https://1x-eng.github.io/blog/"
languageCode = "en-us"
title = "a dystopian journey into the heart of tech"
theme = "m10c"
googleAnalytics = "G-0Q0C7S8K6Z"

[params]
  author = "Pruthvi Kumar"
  description = "confessions of a serial key puncher: the life and times of a coder."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/1x-eng"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://au.linkedin.com/in/iampruthvi"

  [[params.social]]
    icon = "layers"
    name = "Stackoverflow"
    url = "https://stackoverflow.com/users/10019687/pruthvi-kumar"
