baseURL = "https://1x-eng.github.io/blog/"
languageCode = "en-us"
title = "a dystopian journey into the heart of tech"
theme = "m10c"
enableEmoji = true
googleAnalytics = "G-0Q0C7S8K6Z"

[build]
  [build.processing]
    [build.processing.css]
      method = "sass"
      options = "expanded"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "monokai"
    lineNos = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[params]
  author = "Pruthvi Kumar"
  description = "confessions of a serial key puncher: the life and times of a coder."
  enableEmoji = true
  enableMetaTags = true

  customCSS = ["css/custom.css"]

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/1x-eng"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://au.linkedin.com/in/iampruthvi"

  [[params.social]]
    icon = "layers"
    name = "Stackoverflow"
    url = "https://stackoverflow.com/users/10019687/pruthvi-kumar"
